export const TRADE_SOURCES = {
  MANUAL: "MANUAL",
  SYSTEM: "SYSTEM",
  WELLS_FARGO: "WELLS_FARGO",
} as const;

export const RECONCILIATION_STATUS = {
  MANUAL_PENDING: "MANUAL_PENDING",
  MATCHED: "MATCHED",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  SUPERSEDED_BY_WELLS: "SUPERSEDED_BY_WELLS",
  SUPERSEDED_BY_MANUAL: "SUPERSEDED_BY_MANUAL",
  UNMATCHED: "UNMATCHED",
} as const;

export const RECONCILIATION_FLAG_TYPE = "Trade Reconciliation Review";
